<Project>

  <Import Project="$(MSBuildThisFileDirectory)../Directory.Build.props"
          Condition=" Exists('$(MSBuildThisFileDirectory)../Directory.Build.props') "
  />

  <PropertyGroup>
    <!-- Include api comments for nuget packages -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(CI)' == 'true' OR '$(TF_BUILD)' == 'true' ">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup>
		<GlobalNugetPackageTitle>Csproj.Sdk</GlobalNugetPackageTitle>
		<GlobalNugetPackageAuthor>sator-imaging</GlobalNugetPackageAuthor>
		<GlobalNugetRepositoryUrl>https://github.com/sator-imaging/Csproj.Sdk</GlobalNugetRepositoryUrl>
		<GlobalNugetProjectUrl>https://github.com/sator-imaging</GlobalNugetProjectUrl>
		<GlobalNugetTags>unity; csproj; msbuild; visual studio; legacy; sdk style; migrate; migration; convert; converter</GlobalNugetTags>
		<GlobalNugetPackageDescription>$(GlobalNugetRepositoryUrl)</GlobalNugetPackageDescription>
		<GlobalNugetPackageReleaseNote>$(GlobalNugetRepositoryUrl)</GlobalNugetPackageReleaseNote>
		<GlobalNugetPackageCopyright>$(GlobalNugetProjectUrl)</GlobalNugetPackageCopyright>
	</PropertyGroup>

  <ItemGroup>
		<PackageReference Include="SatorImaging.MeticulousAnalyzer" Version="*-*">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
